name: QA test Pipeline

on:
  workflow_dispatch:

        jobs:
          test:
              runs-on: ubuntu-latest
                  steps:
                        - run: echo "QA workflow triggered successfully! check"  


