###############################################################################
# Workflow: Build ➜ Container‑Analysis Scan ➜ Promote
###############################################################################
name: Build ➜ Notify

on:
  repository_dispatch:
    types: [app-code-change]

###############################################################################
# Global environment variables
###############################################################################
env:
  WORKLOAD_IDENTITY_PROVIDER: 'projects/954176678706/locations/global/workloadIdentityPools/github-demo-pool/providers/github'
  SERVICE_ACCOUNT:            'github-action-wif@sivaprasad-426906.iam.gserviceaccount.com'

  QUAR_IMAGE_REGISTRY:   us-central1-docker.pkg.dev/sivaprasad-426906/cloud-run-source-deploy
  #SECURE_IMAGE_REGISTRY: us-central1-docker.pkg.dev/decent-creek-464109-p6/secure-repo
  GAR_LOCATION:          us-central1

  PROJECT_ID: sivaprasad-426906       # GCP project for API calls
  LOCATION:   us-central1                   # Container Analysis location

###############################################################################
# Job 1: Build and push changed Dockerfiles to the quarantine registry
###############################################################################
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: { contents: read, id-token: write }

    outputs:
      built_images: ${{ steps.collect.outputs.images_json }}
      repo_name:    ${{ steps.clone_repo.outputs.REPO_NAME }}
      commit_tag:   ${{ github.event.client_payload.sha }}

    steps:
      # Checkout orchestration repository
      - uses: actions/checkout@v3

      # Clone the application repository at the triggering SHA
      - id: clone_repo
        name: Clone application repository
        run: |
          REPO_FULL="${{ github.event.client_payload.repository }}"
          REPO_NAME="${REPO_FULL#*/}"
          git clone https://x-access-token:${{ secrets.BUILDER_REPO_TOKEN }}@github.com/$REPO_FULL "$REPO_NAME"
          cd "$REPO_NAME"
          git checkout "${{ github.event.client_payload.sha }}"
          echo "REPO_NAME=$REPO_NAME" >> "$GITHUB_OUTPUT"
      # Resolve base commit (empty tree on first run)
      - id: base
        name: Resolve base commit
        run: |
          cd "${{ steps.clone_repo.outputs.REPO_NAME }}"
          if git rev-parse HEAD~1 >/dev/null 2>&1; then
            echo "sha=$(git rev-parse HEAD~1)" >> "$GITHUB_OUTPUT"
          else
            echo "sha=4b825dc642cb6eb9a060e54bf8d69288fbee4904" >> "$GITHUB_OUTPUT"
          fi
      # Detect Dockerfiles that changed
      - id: diff
        name: Detect changed Dockerfiles
        uses: tj-actions/changed-files@v46
        with:
          token: ${{ github.token }}
          path: ${{ steps.clone_repo.outputs.REPO_NAME }}
          base_sha: ${{ steps.base.outputs.sha }}
          sha:      ${{ github.event.client_payload.sha }}
          use_rest_api: false
          files: |
            **/Dockerfile*
      # Authenticate to Google Cloud
      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account:            ${{ env.SERVICE_ACCOUNT }}

      # Set up Buildx builder
      - uses: docker/setup-buildx-action@v2

      # Configure Docker for Artifact Registry
      - name: Configure docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

      # Build and push each changed Dockerfile
      - name: Build and push images
        run: |
          set -e
          REPO="${{ steps.clone_repo.outputs.REPO_NAME }}"
          SHA="${{ github.event.client_payload.sha }}"
          cd "$REPO"
          > /tmp/built.txt
          for FILE in ${{ steps.diff.outputs.all_changed_files }}; do
            [[ "$FILE" != *Dockerfile* ]] && continue
            DIR=$(dirname "$FILE")
            COMP=$(basename "$FILE" | sed -E 's/^Dockerfile[-\.]?//')
            COMP=${COMP:-default}
            TAG="$REPO-$COMP:insecure-$SHA"
            FULL="$QUAR_IMAGE_REGISTRY/$TAG"
            docker build -f "$FILE" -t "$FULL" "$DIR"
            docker push "$FULL"
            echo "$FULL" >> /tmp/built.txt
          done
      # Collect list of built images
      - id: collect
        name: Collect built image list
        run: |
          if [ -s /tmp/built.txt ]; then
            jq -Rsc 'split("\n")[:-1]' /tmp/built.txt > /tmp/list.json
            echo "images_json=$(cat /tmp/list.json)" >> "$GITHUB_OUTPUT"
          else
            echo "images_json=[]" >> "$GITHUB_OUTPUT"
          fi
###############################################################################
# Job 2: Notifying through Mail
###############################################################################
  send_email:
    runs-on: ubuntu-latest # Runner environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Get repository code

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq # Install JSON processor

      - name: Send email via SendGrid API
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }} # Your SendGrid API key
          TO_EMAIL: mailtosiva369@gmail.com # Recipient email
          FROM_EMAIL: mailtosiva369@gmail.com # Verified sender email
          SUBJECT: GitHub Actions Workflow Notification # Email subject
          BODY_TEXT: | # Email body content
            Hello,

            Your GitHub Actions workflow has completed successfully!
            Repository: ${{ github.repository }}
            Workflow: ${{ github.workflow }}
            Run ID: ${{ github.run_id }}
            Commit: ${{ github.sha }}

            To approve and sign the image, please visit:
            https://github.com/${{ github.repository }}/actions/workflows/approvesign.yml
            Click "Run Workflow" and enter the image URI.

            Best regards,
            GitHub Actions Bot
        run: |
          # Construct JSON payload for SendGrid API
          JSON_PAYLOAD=$(jq -n \
            --arg to_email "$TO_EMAIL" \
            --arg from_email "$FROM_EMAIL" \
            --arg subject "$SUBJECT" \
            --arg body_text "$BODY_TEXT" \
            '{
              personalizations: [
                {
                  to: [
                    {
                      email: $to_email
                    }
                  ]
                }
              ],
              from: {
                email: $from_email
              },
              subject: $subject,
              content: [
                {
                  type: "text/plain",
                  value: $body_text
                }
              ]
            }')

          echo "Sending email to $TO_EMAIL from $FROM_EMAIL with subject: $SUBJECT"

          # Send email using curl to SendGrid API
          CURL_RESPONSE=$(curl -s -X POST \
            https://api.sendgrid.com/v3/mail/send \
            -H "Authorization: Bearer $SENDGRID_API_KEY" \
            -H "Content-Type: application/json" \
            -d "$JSON_PAYLOAD" \
            -w "\nHTTP_STATUS:%{http_code}")

          # Extract HTTP status and response body
          HTTP_STATUS=$(echo "$CURL_RESPONSE" | sed -n 's/.*HTTP_STATUS:\([0-9]*\)/\1/p')
          RESPONSE_BODY=$(echo "$CURL_RESPONSE" | sed 's/HTTP_STATUS:[0-9]*//')

          echo "SendGrid API Response (HTTP Status: $HTTP_STATUS):"
          echo "$RESPONSE_BODY"

          # Check for successful HTTP status (2xx)
          if [ "$HTTP_STATUS" -ge 200 ] && [ "$HTTP_STATUS" -lt 300 ]; then
            echo "Email sent successfully! HTTP Status: $HTTP_STATUS"
          else
            echo "Error sending email. HTTP Status: $HTTP_STATUS"
            exit 1 # Fail the step on error
          fi          
