name: Send Email Notification (via Action)

on:
  workflow_dispatch: # Allows manual triggering
  push:
    branches:
      - main # Trigger on push to main

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Send email via Peter Evans SendGrid Action
        # Use the action directly. No need for 'jq' or complex 'curl' commands.
        uses: peter-evans/sendgrid-action@v1 # Always check the repo for the latest stable version
        with:
          api-key: ${{ secrets.SENDGRID_API_KEY }}
          to: sivaprasad3697@gmail.com
          from: mailtosiva369@gmail.com
          subject: GitHub Actions Workflow Notification
          content: | # Multi-line content is supported, and expressions are evaluated
            Hello,

            Your GitHub Actions workflow has completed successfully!
            Repository: ${{ github.repository }}
            Workflow: ${{ github.workflow }}
            Run ID: ${{ github.run_id }}
            Commit: ${{ github.sha }}

            Best regards,
            GitHub Actions Bot