name: Trigger QA Workflow

on:
  workflow_dispatch:

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.BUILDER_REPO_TOKEN }}
          repository: sivaprasadhub/central-repo
          event-type: qa-pipeline
          client-payload: |
            {
              "repository": "${{ github.repository }}",
              "sha": "${{ github.sha }}"
            }
